abstract: 1
common_fields: 0

objects: 
    user_create: 
        extends: user
        instance: 
            id_object: 
                field_value: id_user_create
                
    shared_user: 
        extends: user
        instance: 
            id_object: unset
            
fields: 
    name: 
        label: Nom
        required: 1
        
    owner_type: 
        label: Type propriétaire
        values: 
            array: owner_types
        required: 1
        default_value: 2
        
    id_owner: 
        label: Propriétaire
        type: id_object
        required: 1
        
    shared_users: 
        label: Partage utilisateurs
        type: items_list
        items_data_type: id_object
        items_braces: 1
        object: shared_user
        input: 
            type: search_user
        
    shared_groups: 
        label: Partage groupes
        type: items_list
        items_data_type: id_object
        items_braces: 1
        values: 
            callback: 
                method: getUserGroupsArray
                params: 
                    - 1
                    - 1
        
    is_default: 
        label: Configuration par défaut
        type: bool
        default_value: 0
        
    id_user_create: 
        label: Créé par
        type: id_object
        object: user_create
        default_value: 0
        
forms: 
    default:
        rows: 
            name: 
                field: name
            is_default: 
                field: is_default            
            owner_type: 
                field: owner_type
                show: 
                    callback: isNotLoaded
            group: 
              custom: 1
              label: Groupe
              show: 
                    callback: isNotLoaded
              input_name: id_group
              data_type: id
              value: 
                  callback: getIdGroup
              content: 
                  callback: renderGroupInput
              display_if: 
                  field_name: owner_type
                  show_values: 1
                  
    shares: 
        title: Partages
        rows: 
            shared_users: 
                field: shared_users
            shared_groups: 
                field: shared_groups        

lists_cols: 
    owner: 
        label: Propriétaire
        value: 
            callback: displayOwner
    owner_nom_url: 
        label: Propriétaire
        value:
            callback:
                method: displayOwner
                params: 
                    - 1
    utilisation: 
        label: Utilisation
        value: 
            callback: displayUtilisation
        
filters_panels: 
    default: 
        filters: 
            - field: obj_module
            - field: obj_name
            - field: list_type
            - field: list_name
            - field: owner_type
            - custom: 1
              label: Utilisateur
              field: id_user
              type: user
            - custom: 1
              label: Utilisateur (groupes inclus) 
              field: id_user_with_groups
              type: user
            - custom: 1
              label: Groupe
              field: id_group
              type: value
              input: 
                  type: search_group
                  
lists: 
    base: 
        checkboxes: 1
        bulk_actions:
            - label: supprimer les configurations sélectionnées
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        sort_field: id
        sort_way: asc
        edit_btn: 1
        edit_form: default
        delete_btn: 1
        extra_btn: 
            callback: getListExtraButtons
                    
    default: 
        extends: base
        title: 
            callback: getListTitle
        configurable: 1
        enable_search: 0
        enable_sort: 1
        add_form_name: default
        add_btn_label: Nouvelle configuration
        n: 0
        pagination: 0
        cols: 
            name:
            id_user_create: 
            owner_nom_url: 
            utilisation: 
            shared_users:
            shared_groups:
            
    globale: 
        extends: base
        title: Configurations des liste
        filters_panel: default
        filters_panel_open: 1
        bulk_actions: 
            1: 
                label: Générer CSV
                icon: fas_file-excel
                onclick: setSelectedObjectsAction($(this), 'list_id', 'generateBulkCsv', {}, 'bulk_csv', null, true)
        configurable: 1
        enable_search: 1
        n: 10
        sort_way: desc
        cols: 
                
    user: 
        extends: base
        title: 
            callback: getListTitle
        configurable: 0
        enable_search: 1
        enable_sort: 1
        sort_way: desc
        n: 10
        cols: